import "./globals.css";
import type { Metadata } from "next";
import IranSans from "@/config/font";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/providers/theme/ThemeProvider";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/providers/query/Query";
import DashboardLayout from "@/components/layout/DashboardLayout";
import SessionProvider from "@/providers/session-provider/SessionProvider";
import { auth } from "@/auth/auth";

export const metadata: Metadata = {
  title: "Manage student",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={cn(IranSans.variable, "antialiased")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <SessionProvider session={session}>
              <Toaster position="top-center" />
              <DashboardLayout>{children}</DashboardLayout>
            </SessionProvider>
          </ReactQueryProvider>
        </ThemeProvider>{" "}
      </body>
    </html>
  );
}
